# Nome do aplicativo, como ele será identificado.
name: bill_splitter_app
# Uma breve descrição do que o aplicativo faz.
description: Um aplicativo para dividir contas com amigos.
# 'none' impede que o pacote seja acidentalmente publicado no pub.dev.
publish_to: 'none' 

# A versão atual do aplicativo.
version: 1.0.0+1

# Define a versão do SDK do Dart com a qual o projeto é compatível.
environment:
  sdk: '>=3.0.0 <4.0.0'

# Lista de dependências que o aplicativo precisa para funcionar.
dependencies:
  # Pacote principal do Flutter, necessário para construir a UI.
  flutter:
    sdk: flutter
  
  # Pacote para ler e escrever dados no formato CSV.
  csv: ^5.1.1
  
  # Pacote para encontrar o caminho de diretórios locais no dispositivo (para salvar os CSVs).
  path_provider: ^2.1.3
  
  # Pacote para formatação, especialmente usado para datas.
  intl: ^0.19.0

  # Pacote para criar gráficos bonitos e customizáveis.
  fl_chart: ^0.68.0

  # Pacote de ícones no estilo iOS.
  cupertino_icons: ^1.0.2

# Dependências usadas apenas durante o desenvolvimento (testes, etc.).
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Ferramentas de análise de código para manter o código limpo e padronizado.
  flutter_lints: ^3.0.0

# Configurações específicas do Flutter.
flutter:
  # Indica que o projeto usa Material Design.
  uses-material-design: true

